clusterissuer:
  name: letsencrypt
  email: eduartua@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  solvers:
  - http01:
      ingress:
        class: nginx
cert-manager:
  enabled: true
  ingressShim:
    defaultIssuerName: "letsencrypt"
    defaultIssuerKind: "ClusterIssuer"

# Automatically install CRDs.
# WARNING: removal of the cert-manager helm chart WILL REMOVE CRDs as well, including Certificates!!
#installCRDs: true
